# -*- coding: utf-8 -*-
"""Predicting Vfb and Vt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKWKj3Njaiv4o-kmUd57NhHeNViSt4fU
"""

import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# User settings
# ==========================================
substrate_type = 'n'      # 'p' for p-type Si substrate (NMOS case)
                          # 'n' for n-type Si substrate (PMOS case)

N_min = 1e14              # minimum doping concentration (cm^-3)
N_max = 1e18              # maximum doping concentration (cm^-3)
num_points = 500

T = 300.0                 # temperature (K)

# Gate metal work function
phi_m = 4.10              # eV, Al gate

# Define multiple oxide scenarios here
oxide_scenarios = [
    {"label": "k=6, tox=20 nm", "k_ox": 6.0, "tox_nm": 20.0},
    {"label": "k=6, tox=50 nm", "k_ox": 6.0, "tox_nm": 50.0},

    # Add more if you want:
    # {"label": "SiO2, tox=20 nm", "k_ox": 3.9, "tox_nm": 20.0},
]

# Silicon constants
ni = 1e10                 # cm^-3
chi_si = 4.05             # eV
Eg_si = 1.12              # eV
eps_si_rel = 11.7         # relative permittivity of Si

# Example point to mark on plots
N_example = 2e15        # cm^-3

# ==========================================
# Physical constants
# ==========================================
q = 1.602176634e-19         # C
k_B_eV = 8.617333262145e-5  # eV/K
eps0 = 8.854187817e-14      # F/cm

Vt_thermal = k_B_eV * T     # kT/q in V
eps_si = eps_si_rel * eps0  # F/cm

# ==========================================
# Doping range
# ==========================================
N = np.logspace(np.log10(N_min), np.log10(N_max), num_points)

# Fermi potential magnitude
phi_F = Vt_thermal * np.log(N / ni)   # V

# ==========================================
# Flatband voltage
# ==========================================
if substrate_type.lower() == 'p':
    # p-type substrate -> NMOS case
    phi_s = chi_si + Eg_si / 2 + phi_F
    Vfb = phi_m - phi_s

    x_label = 'Acceptor concentration, $N_A$ (cm$^{-3}$)'
    title_vfb = 'Al-gated p-type Si: $V_{FB}$ vs Acceptor Concentration'
    title_vth = 'Al-gated p-type Si (NMOS case): $V_T$ vs Acceptor Concentration'
    device_label = 'NMOS on p-type substrate'

elif substrate_type.lower() == 'n':
    # n-type substrate -> PMOS case
    phi_s = chi_si + Eg_si / 2 - phi_F
    Vfb = phi_m - phi_s

    x_label = 'Donor concentration, $N_D$ (cm$^{-3}$)'
    title_vfb = 'Al-gated n-type Si: $V_{FB}$ vs Donor Concentration'
    title_vth = 'Al-gated n-type Si (PMOS case): $V_T$ vs Donor Concentration'
    device_label = 'PMOS on n-type substrate'

else:
    raise ValueError("substrate_type must be 'p' or 'n'")

# ==========================================
# Example-point calculations
# ==========================================
phi_F_ex = Vt_thermal * np.log(N_example / ni)

if substrate_type.lower() == 'p':
    phi_s_ex = chi_si + Eg_si / 2 + phi_F_ex
    Vfb_ex = phi_m - phi_s_ex
else:
    phi_s_ex = chi_si + Eg_si / 2 - phi_F_ex
    Vfb_ex = phi_m - phi_s_ex

# ==========================================
# Helper function for annotation placement
# ==========================================
def annotate_point(ax, x, y, text, xoff=10, yoff=10):
    ax.plot(x, y, 'o', markersize=5)
    ax.annotate(
        text,
        xy=(x, y),
        xytext=(xoff, yoff),
        textcoords='offset points',
        bbox=dict(boxstyle='round,pad=0.25', alpha=0.8),
        arrowprops=dict(arrowstyle='->', lw=1)
    )

# ==========================================
# Plot Vfb
# Note: Vfb does NOT depend on tox or kox in this ideal model
# ==========================================
fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(N, Vfb, linewidth=2, label='$V_{FB}$')
ax.axvline(N_example, linestyle='--', linewidth=1.5, alpha=0.8,
           label=f'Example N = {N_example:.2e} cm$^{{-3}}$')
annotate_point(ax, N_example, Vfb_ex, f'$V_{{FB}}$ = {Vfb_ex:.3f} V')

ax.set_xscale('log')
ax.set_xlabel(x_label)
ax.set_ylabel('Flatband voltage, $V_{FB}$ (V)')
ax.set_title(title_vfb)
ax.grid(True, which='both', alpha=0.3)
ax.legend()
plt.tight_layout()
plt.show()

# ==========================================
# Plot Vth for multiple oxide scenarios
# ==========================================
fig, ax = plt.subplots(figsize=(8, 5))

# Vertical line at example concentration
ax.axvline(N_example, linestyle='--', linewidth=1.5, alpha=0.8,
           label=f'Example N = {N_example:.2e} cm$^{{-3}}$')

# Offsets for annotation boxes so they do not stack directly on top of each other
y_offsets = [14, -18, 32, -36, 50, -54, 68, -72]

for i, scenario in enumerate(oxide_scenarios):
    k_ox = scenario["k_ox"]
    tox_nm = scenario["tox_nm"]
    label = scenario["label"]

    tox_cm = tox_nm * 1e-7
    eps_ox = k_ox * eps0
    Cox = eps_ox / tox_cm

    Qd_max = np.sqrt(4 * eps_si * q * N * phi_F)

    if substrate_type.lower() == 'p':
        Vth = Vfb + 2 * phi_F + Qd_max / Cox
        Qd_ex = np.sqrt(4 * eps_si * q * N_example * phi_F_ex)
        Vth_ex = Vfb_ex + 2 * phi_F_ex + Qd_ex / Cox
    else:
        Vth = Vfb - 2 * phi_F - Qd_max / Cox
        Qd_ex = np.sqrt(4 * eps_si * q * N_example * phi_F_ex)
        Vth_ex = Vfb_ex - 2 * phi_F_ex - Qd_ex / Cox

    ax.plot(N, Vth, linewidth=2, label=f'{label}')

    yoff = y_offsets[i % len(y_offsets)]
    annotate_point(ax, N_example, Vth_ex, f'{label}\n$V_T$ = {Vth_ex:.3f} V', xoff=10, yoff=yoff)


plt.ylim(-5, 1)
ax.set_xscale('log')
ax.set_xlabel(x_label)
ax.set_ylabel('Threshold voltage, $V_T$ (V)')
ax.set_title(title_vth)
ax.grid(True, which='both', alpha=0.3)
ax.legend()
plt.tight_layout()
plt.show()

# ==========================================
# Print example values
# ==========================================
print('========================================')
print(f'Substrate type: {substrate_type}')
print(f'Device interpretation: {device_label}')
print(f'At N = {N_example:.2e} cm^-3:')
print(f'  phi_F = {phi_F_ex:.4f} V')
print(f'  phi_s = {phi_s_ex:.4f} eV')
print(f'  V_FB  = {Vfb_ex:.4f} V')
print('----------------------------------------')

for scenario in oxide_scenarios:
    k_ox = scenario["k_ox"]
    tox_nm = scenario["tox_nm"]
    label = scenario["label"]

    tox_cm = tox_nm * 1e-7
    eps_ox = k_ox * eps0
    Cox = eps_ox / tox_cm

    Qd_ex = np.sqrt(4 * eps_si * q * N_example * phi_F_ex)

    if substrate_type.lower() == 'p':
        Vth_ex = Vfb_ex + 2 * phi_F_ex + Qd_ex / Cox
    else:
        Vth_ex = Vfb_ex - 2 * phi_F_ex - Qd_ex / Cox

    print(f'{label}:')
    print(f'  Cox = {Cox:.4e} F/cm^2')
    print(f'  V_T = {Vth_ex:.4f} V')
    print('----------------------------------------')

print('========================================')