# -*- coding: utf-8 -*-
"""doping profile form MOScap CV data vibe coded.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYtWP37ITve1qhWbRCTZtF2DwTek-h7i
"""

# -*- coding: utf-8 -*-
"""doping profile form MOScap CV data vibe coded.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYtWP37ITve1qhWbRCTZtF2DwTek-h7i
"""

# -*- coding: utf-8 -*-
"""
MOSCAP C-V comparison + substrate doping extraction
using the 1/C^2 vs V method

Based on the earlier MOSCAP comparison script, but stripped down and
re-focused for substrate doping extraction.

What this script does
---------------------
1. Loads MOSCAP C-V data from multiple folders
2. Averages repeated curves within each folder / sweep direction
3. Optionally applies series-resistance correction
4. Plots:
   - averaged raw C-V
   - averaged raw + corrected C-V
   - averaged 1/C^2 vs V with linear fit in a user-defined depletion window
5. Extracts substrate doping from the fitted 1/C^2 slope

Method used
-----------
N_sub = 2 / ( q * eps_s * A^2 * d(1/C^2)/dV )

Units:
- C in F
- A in cm^2
- eps_s in F/cm
- V in V
- N_sub comes out in cm^-3

Sign convention:
- positive slope  -> acceptors (p-type)
- negative slope  -> donors (n-type)

Important:
----------
Choose the fit window so it covers the approximately linear depletion region
only. Do not fit accumulation or deep inversion.
"""

import os
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch


# =========================================================
# USER SETTINGS
# =========================================================

DATASETS = [


    {
        'folder': r'/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/MOSCap Data_clean/3-6-26, 1hr 9_9, shadowmask',
        'label': '(5-10 ohm p-type wafer)',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },
]
'''
    {
        'folder': r'/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/MOSCap Data_clean/3-3-26, 3hr 9_9, shadowmask',
        'label': '9:9, 3hr (45nm), standard RCA clean',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },

    {
        'folder': r'/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/MOSCap Data_clean/3-12-26, 3hr 9_9, HF last, shadow mask',
        'label': '9:9, 3hr (45nm), HF-Last RCA clean',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },
    {
        'folder': r'/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/MOSCap Data_clean/3-15-26, 80min 9_9, HF last, shadow mask',
        'label': '9:9, 80min (20nm), HF-Last RCA clean',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },
    {
        'folder': r'/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/MOSCap Data_clean/3-16-26, 80min 9_9, 450C 30min O2 anneal, HF last, shadow mask',
        'label': '9:9, 80min (20nm), HF-Last RCA clean, 450C O2 anneal',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },
]


    {
        'folder': '/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/4_28_shortthrow_9-9_15min_hflast',
        'label': '(5-10 ohm p-type wafer)',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },
]

    {
        'folder': '/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/5_4_5minpred_60mindrivein_15minOxide_hflast',
        'label': '5 min 800C predep with Phosphorous spin on dopant, 60 min 1100c drive in (5-10 ohm p-type wafer)',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },
    {
        'folder': '/content/drive/MyDrive/hackerfinalproject6-1backup/Hfab final project/4_29_ntype_shortthrow_9-9_15min_hflast/4_29_ntype_shortthrow_9-9_15min_hflast',
        'label': '(1-10 ohm n-type wafer)',
        'size_to_compare': 'Small',
        'area_mm2': 0.2,
    },

'''

TARGET_FREQUENCY = '100KHz'

# File selection controls
Include_10KHzPN = 0
Include_10KHzNP = 0
Include_100KHzPN = 1
Include_100KHzNP = 1
Include_1MHzPN = 0
Include_1MHzNP = 0

Include_all_appends = 1
Appends_to_inlcude_10KHzPN = []
Appends_to_inlcude_10KHzNP = []
Appends_to_inlcude_100KHzPN = [0, 2, 3, 5]
Appends_to_inlcude_100KHzNP = [2, 3, 5]
Appends_to_inlcude_1MHzPN = []
Appends_to_inlcude_1MHzNP = []

# Averaging controls
COMMON_VOLTAGE_STEP = 0.05
MIN_POINTS_REQUIRED = 3

# C-V / voltage plot x-axis controls
CV_USE_XLIM = True
CV_XMIN = -5
CV_XMAX = 5

# Y-axis controls for C-V plots
# If CV_AUTO_YLIM_TO_XLIM is True, the C-V y-axis is scaled only from
# data points inside CV_XMIN to CV_XMAX. This prevents off-screen data
# from stretching/compressing the visible plot.
CV_AUTO_YLIM_TO_XLIM = True
CV_Y_PADDING_FRACTION = 0.08

# Set CV_USE_YLIM = True if you want direct manual y-axis control for C-V plots.
# Manual limits override CV_AUTO_YLIM_TO_XLIM. Use None for one side to leave it automatic.
CV_USE_YLIM = False
CV_YMIN = None
CV_YMAX = None

# Y-axis controls for 1/C^2 plots
INVC2_AUTO_YLIM_TO_XLIM = True
INVC2_Y_PADDING_FRACTION = 0.08

# Set INVC2_USE_YLIM = True if you want direct manual y-axis control for 1/C^2 plots.
# Manual limits override INVC2_AUTO_YLIM_TO_XLIM. Use None for one side to leave it automatic.
INVC2_USE_YLIM = False
INVC2_YMIN = None
INVC2_YMAX = None

# Series correction
APPLY_SERIES_CORRECTION = False

# Doping extraction settings
DOPING_USE_CORRECTED_CAP = True
DOPING_FIT_VMIN = 1.5
DOPING_FIT_VMAX = 4.5
DOPING_MIN_FIT_POINTS = 5

# Best-fit line label controls
# Set to False to hide the dopant-type/concentration labels on the 1/C^2 plot.
LABEL_DOPING_FIT_LINES = True
DOPING_FIT_LABEL_X_FRACTION = 0.62   # position along each fit line, from 0 to 1
DOPING_FIT_LABEL_FONTSIZE = 9
DOPING_FIT_LABEL_DECIMAL_PLACES = 2
DOPING_FIT_LABEL_SHOW_R2 = False

# Combined corrected-C and 1/C^2 plot controls
# This creates an additional plot with corrected capacitance on the left
# y-axis and 1/C^2 on the right y-axis.
PLOT_COMBINED_CORRECTED_C_AND_INVC2 = True
COMBINED_C_AXIS_COLOR = 'tab:blue'
COMBINED_INVC2_AXIS_COLOR = 'tab:red'
COMBINED_FIT_REGION_COLOR = 'gray'
COMBINED_FIT_REGION_ALPHA = 0.12
COMBINED_SHOW_BEST_FIT_LINE = True
COMBINED_LABEL_DOPING_FIT_LINES = True
COMBINED_FIGSIZE = (11, 6)

# Semiconductor constants for Si
Q_E = 1.602176634e-19          # C
EPS_SI_F_PER_CM = 1.034e-12    # F/cm

# Style controls
FOLDER_COLORMAP = 'tab10'
DIRECTION_MARKERS = {'PN': 'o', 'NP': '^'}
DIRECTION_LINESTYLES = {'PN': 'solid', 'NP': 'dashed'}
RAW_LINEWIDTH = 1.6
RAW_ALPHA = 0.45
CORRECTED_LINEWIDTH = 2.6
CORRECTED_ALPHA = 1.0


# =========================================================
# HELPERS
# =========================================================

def filenameShouldBePlotted(filename):
    if filename.startswith('10KHzPN') and Include_10KHzPN:
        return Appends_to_inlcude_10KHzPN
    elif filename.startswith('10KHzNP') and Include_10KHzNP:
        return Appends_to_inlcude_10KHzNP
    elif filename.startswith('100KHzPN') and Include_100KHzPN:
        return Appends_to_inlcude_100KHzPN
    elif filename.startswith('100KHzNP') and Include_100KHzNP:
        return Appends_to_inlcude_100KHzNP
    elif filename.startswith('1MHzPN') and Include_1MHzPN:
        return Appends_to_inlcude_1MHzPN
    elif filename.startswith('1MHzNP') and Include_1MHzNP:
        return Appends_to_inlcude_1MHzNP
    return False


def tabShouldBePlotted(tab, Appends_to_include):
    if tab in ['Calc', 'Settings']:
        return False
    elif Include_all_appends:
        return True
    elif tab == 'Data' and 0 in Appends_to_include:
        return True
    elif tab == 'Data' and 0 not in Appends_to_include:
        return False
    else:
        suffix = tab[len(tab.rstrip('0123456789')):]
        if suffix == '':
            return False
        try:
            return int(suffix) in Appends_to_include
        except Exception:
            return False


def extractConditionFromFilename(filename):
    if filename.startswith('10KHzPN'):
        return '10KHz', 'PN'
    elif filename.startswith('10KHzNP'):
        return '10KHz', 'NP'
    elif filename.startswith('100KHzPN'):
        return '100KHz', 'PN'
    elif filename.startswith('100KHzNP'):
        return '100KHz', 'NP'
    elif filename.startswith('1MHzPN'):
        return '1MHz', 'PN'
    elif filename.startswith('1MHzNP'):
        return '1MHz', 'NP'
    return 'Unknown', 'Unknown'


def dataset_label_from_config(cfg):
    if cfg.get('label'):
        return str(cfg['label'])
    return os.path.basename(os.path.normpath(cfg['folder']))


def get_folder_colors(dataset_labels):
    cmap = plt.get_cmap(FOLDER_COLORMAP)
    colors = {}
    for i, label in enumerate(dataset_labels):
        colors[label] = cmap(i % getattr(cmap, 'N', 10))
    return colors


def show_plot(fig):
    fig.tight_layout()
    plt.show()
    plt.close(fig)


def _is_number(x):
    return x is not None and np.isfinite(x)


def _manual_or_auto_ylim_from_visible_x(
    ax,
    xy_pairs,
    use_manual_ylim=False,
    ymin=None,
    ymax=None,
    auto_ylim_to_xlim=True,
    padding_fraction=0.08,
):
    """
    Fix Matplotlib's default behavior where y autoscaling still includes
    data outside a manually-set x-axis window.

    Parameters
    ----------
    ax : matplotlib axis
    xy_pairs : list of (x_array, y_array)
        The plotted x/y data that should be considered for y-axis scaling.
        Include upper/lower fill_between bounds if those should stay visible.
    use_manual_ylim : bool
        If True, manual ymin/ymax are applied and auto-scaling is skipped.
    ymin, ymax : float or None
        Manual y limits. If only one is provided, the other side uses the
        current Matplotlib limit.
    auto_ylim_to_xlim : bool
        If True and CV_USE_XLIM is True, compute y limits using only points
        with CV_XMIN <= x <= CV_XMAX.
    padding_fraction : float
        Fractional padding added above/below the visible y range.
    """
    if use_manual_ylim:
        current_ymin, current_ymax = ax.get_ylim()
        ax.set_ylim(
            ymin if _is_number(ymin) else current_ymin,
            ymax if _is_number(ymax) else current_ymax,
        )
        return

    if not (auto_ylim_to_xlim and CV_USE_XLIM):
        return

    visible_y_values = []

    for x, y in xy_pairs:
        x = np.asarray(x, dtype=float)
        y = np.asarray(y, dtype=float)

        good = np.isfinite(x) & np.isfinite(y) & (x >= CV_XMIN) & (x <= CV_XMAX)
        if np.any(good):
            visible_y_values.append(y[good])

    if len(visible_y_values) == 0:
        return

    y_all = np.concatenate(visible_y_values)
    y_all = y_all[np.isfinite(y_all)]

    if len(y_all) == 0:
        return

    y_min = np.nanmin(y_all)
    y_max = np.nanmax(y_all)

    if not (np.isfinite(y_min) and np.isfinite(y_max)):
        return

    y_span = y_max - y_min
    if y_span <= 0:
        # Create a small, sensible window around a flat trace.
        center = y_min
        y_span = abs(center) * 0.10 if center != 0 else 1.0
        y_min = center - 0.5 * y_span
        y_max = center + 0.5 * y_span

    pad = padding_fraction * y_span
    ax.set_ylim(y_min - pad, y_max + pad)


def safe_frequency_array_from_label(frequency, npts):
    if frequency == '10KHz':
        return np.full(npts, 1e4, dtype=float)
    if frequency == '100KHz':
        return np.full(npts, 1e5, dtype=float)
    if frequency == '1MHz':
        return np.full(npts, 1e6, dtype=float)
    return np.full(npts, np.nan, dtype=float)


def calcSeriesResAdjC(C, G, f):
    """
    Series-resistance correction for measured parallel capacitance.
    """
    C = np.asarray(C, dtype=float)
    G = np.asarray(G, dtype=float)
    f = np.asarray(f, dtype=float)

    with np.errstate(divide='ignore', invalid='ignore'):
        denom = (1 + (G / (2 * math.pi * f * C))**2) * G
        Rs = ((G / (2 * math.pi * f * C))**2) / denom
        alpha = G - (G**2 + (2 * math.pi * f * C)**2) * Rs
        C_adj = (((G**2) + (2 * math.pi * f * C)**2) * C) / (alpha**2 + (2 * math.pi * f * C)**2)

    C_adj = np.where(np.isfinite(C_adj), C_adj, np.nan)
    return C_adj


def compute_inverse_c2(capacitance):
    c = np.asarray(capacitance, dtype=float)
    out = np.full_like(c, np.nan, dtype=float)
    mask = np.isfinite(c) & (c > 0)
    out[mask] = 1.0 / (c[mask] ** 2)
    return out


def makeCommonVoltageGrid(curves, step):
    xmin = max(np.nanmin(curve['voltage']) for curve in curves)
    xmax = min(np.nanmax(curve['voltage']) for curve in curves)
    if xmax <= xmin:
        return None
    return np.arange(xmin, xmax + step / 2, step)


def average_duplicate_x(x, y):
    df = pd.DataFrame({'x': x, 'y': y}).dropna()
    if len(df) < 2:
        return None, None
    df = df.groupby('x', as_index=False)['y'].mean().sort_values('x')
    return df['x'].to_numpy(), df['y'].to_numpy()


def interpolateCurveToGrid(x, y, common_grid):
    x2, y2 = average_duplicate_x(x, y)
    if x2 is None or len(x2) < 2:
        return None
    return np.interp(common_grid, x2, y2)


def comparison_size_label(dataset_cfgs):
    sizes_used = []
    for cfg in dataset_cfgs:
        s = cfg.get('size_to_compare', None)
        if s is not None and s not in sizes_used:
            sizes_used.append(s)

    if len(sizes_used) == 0:
        return 'comparison size'
    if len(sizes_used) == 1:
        return sizes_used[0]
    return 'Mixed sizes: ' + ', '.join(sizes_used)


def add_comparison_legends(ax, folder_colors, include_curve_type=False):
    folder_handles = [
        Line2D([0], [0], color=color, lw=2, label=label)
        for label, color in folder_colors.items()
    ]
    direction_handles = [
        Line2D([0], [0],
               color='black',
               marker=DIRECTION_MARKERS[d],
               linestyle=DIRECTION_LINESTYLES[d],
               lw=2,
               markersize=7,
               label=d)
        for d in ['PN', 'NP']
    ]

    leg1 = ax.legend(handles=folder_handles, title='Folder / condition', loc='upper right')
    ax.add_artist(leg1)

    leg2 = ax.legend(handles=direction_handles, title='Direction', loc='lower right')
    ax.add_artist(leg2)

    if include_curve_type:
        curve_type_handles = [
            Line2D([0], [0], color='black', lw=RAW_LINEWIDTH, alpha=RAW_ALPHA, linestyle=':', label='raw'),
            Line2D([0], [0], color='black', lw=CORRECTED_LINEWIDTH, alpha=CORRECTED_ALPHA, linestyle='-', label='corrected'),
        ]
        ax.legend(handles=curve_type_handles, title='Curve type', loc='center right')


def format_doping_fit_label(fit):
    """Return a Matplotlib label containing dopant type and concentration."""
    doping = fit.get('doping_cm3_abs', np.nan)
    slope = fit.get('slope', np.nan)

    if not (np.isfinite(doping) and doping > 0 and np.isfinite(slope)):
        return None

    if slope > 0:
        type_text = 'p-type (acceptor)'
        concentration_symbol = r'N_A'
    elif slope < 0:
        type_text = 'n-type (donor)'
        concentration_symbol = r'N_D'
    else:
        return None

    exponent = int(np.floor(np.log10(doping)))
    mantissa = doping / (10 ** exponent)
    concentration_text = (
        rf'${concentration_symbol} = '
        rf'{mantissa:.{DOPING_FIT_LABEL_DECIMAL_PLACES}f}'
        rf'\times 10^{{{exponent}}}\ \mathrm{{cm}}^{{-3}}$'
    )

    label = f'{type_text}\n{concentration_text}'

    if DOPING_FIT_LABEL_SHOW_R2 and np.isfinite(fit.get('r2', np.nan)):
        label += rf'\n$R^2 = {fit["r2"]:.3f}$'

    return label


def fit_inverse_c2_line(voltage, inv_c2, area_mm2, vmin, vmax):
    x = np.asarray(voltage, dtype=float)
    y = np.asarray(inv_c2, dtype=float)

    mask = np.isfinite(x) & np.isfinite(y) & (x >= vmin) & (x <= vmax)
    x_fit = x[mask]
    y_fit = y[mask]

    if len(x_fit) < DOPING_MIN_FIT_POINTS:
        return {
            'npts': len(x_fit),
            'slope': np.nan,
            'intercept': np.nan,
            'r2': np.nan,
            'x_fit': x_fit,
            'y_fit': y_fit,
            'x_line': np.array([]),
            'y_line': np.array([]),
            'doping_cm3_signed': np.nan,
            'doping_cm3_abs': np.nan,
            'carrier_type': 'unknown',
        }

    slope, intercept = np.polyfit(x_fit, y_fit, 1)
    y_pred = slope * x_fit + intercept

    ss_res = np.sum((y_fit - y_pred) ** 2)
    ss_tot = np.sum((y_fit - np.mean(y_fit)) ** 2)
    r2 = np.nan if ss_tot <= 0 else 1 - (ss_res / ss_tot)

    area_cm2 = area_mm2 * 0.01  # 1 mm^2 = 0.01 cm^2

    if (not np.isfinite(area_cm2)) or area_cm2 <= 0 or (not np.isfinite(slope)) or slope == 0:
        doping_signed = np.nan
    else:
        doping_signed = 2.0 / (Q_E * EPS_SI_F_PER_CM * (area_cm2 ** 2) * slope)

    if np.isfinite(slope):
        if slope > 0:
            carrier_type = 'acceptors (p-type)'
        elif slope < 0:
            carrier_type = 'donors (n-type)'
        else:
            carrier_type = 'unknown'
    else:
        carrier_type = 'unknown'

    x_line = np.linspace(vmin, vmax, 200)
    y_line = slope * x_line + intercept if np.isfinite(slope) and np.isfinite(intercept) else np.full_like(x_line, np.nan)

    return {
        'npts': len(x_fit),
        'slope': slope,
        'intercept': intercept,
        'r2': r2,
        'x_fit': x_fit,
        'y_fit': y_fit,
        'x_line': x_line,
        'y_line': y_line,
        'doping_cm3_signed': doping_signed,
        'doping_cm3_abs': abs(doping_signed) if np.isfinite(doping_signed) else np.nan,
        'carrier_type': carrier_type,
    }


# =========================================================
# DATA INGESTION
# =========================================================

def collect_curves_for_dataset(cfg):
    folder = cfg['folder']
    size_to_compare = cfg['size_to_compare']
    dataset_label = dataset_label_from_config(cfg)

    all_curves = []

    if not os.path.isdir(folder):
        print(f"Skipping missing folder: {folder}")
        return all_curves

    for subfolder in os.listdir(folder):
        subfolder_path = os.path.join(folder, subfolder)
        if not (os.path.isdir(subfolder_path) and subfolder == size_to_compare):
            continue

        for filename in os.listdir(subfolder_path):
            appends_to_include = filenameShouldBePlotted(filename)
            if appends_to_include is False:
                continue

            frequency, direction = extractConditionFromFilename(filename)
            if frequency != TARGET_FREQUENCY:
                continue

            sheet = os.path.join(subfolder_path, filename)
            try:
                xls = pd.ExcelFile(sheet)
            except Exception as e:
                print(f"Skipping unreadable file: {sheet} ({e})")
                continue

            for tab in xls.sheet_names:
                if not tabShouldBePlotted(tab, appends_to_include):
                    continue

                try:
                    df = pd.read_excel(sheet, tab)
                except Exception as e:
                    print(f"Skipping unreadable tab: {sheet} | {tab} ({e})")
                    continue

                needed = ['DCV_GB', 'Cp_GB', 'Gp_GB']
                if not all(col in df.columns for col in needed):
                    continue

                temp = df[['DCV_GB', 'Cp_GB', 'Gp_GB']].copy()
                if 'F_GB' in df.columns:
                    temp['F_GB'] = pd.to_numeric(df['F_GB'], errors='coerce')
                else:
                    temp['F_GB'] = np.nan

                temp = temp.apply(pd.to_numeric, errors='coerce').dropna(subset=['DCV_GB', 'Cp_GB', 'Gp_GB'])
                if len(temp) < MIN_POINTS_REQUIRED:
                    continue

                voltage = temp['DCV_GB'].to_numpy(dtype=float)
                capacitance = temp['Cp_GB'].to_numpy(dtype=float)
                conductance = temp['Gp_GB'].to_numpy(dtype=float)
                freq_from_col = temp['F_GB'].to_numpy(dtype=float)

                if np.all(~np.isfinite(freq_from_col)):
                    freq_array = safe_frequency_array_from_label(frequency, len(voltage))
                else:
                    valid = freq_from_col[np.isfinite(freq_from_col)]
                    medf = np.median(valid) if len(valid) else np.nan
                    freq_array = np.where(np.isfinite(freq_from_col), freq_from_col, medf)

                if APPLY_SERIES_CORRECTION:
                    capacitance_corrected = calcSeriesResAdjC(capacitance, conductance, freq_array)
                else:
                    capacitance_corrected = capacitance.copy()

                inv_c2_raw = compute_inverse_c2(capacitance)
                inv_c2_corr = compute_inverse_c2(capacitance_corrected)

                all_curves.append({
                    'dataset_label': dataset_label,
                    'folder': folder,
                    'size': size_to_compare,
                    'frequency': frequency,
                    'direction': direction,
                    'filename': filename,
                    'tab': tab,
                    'voltage': voltage,
                    'capacitance': capacitance,
                    'capacitance_corrected': capacitance_corrected,
                    'inverse_c2': inv_c2_raw,
                    'inverse_c2_corrected': inv_c2_corr,
                    'area_mm2': cfg.get('area_mm2', np.nan),
                })

    return all_curves


def group_curves(curves, metric_key, group_keys):
    grouped = {}
    for curve in curves:
        key = tuple(curve[k] for k in group_keys)
        grouped.setdefault(key, []).append(curve)

    results = {}
    for key, members in grouped.items():
        common_grid = makeCommonVoltageGrid(members, COMMON_VOLTAGE_STEP)
        if common_grid is None or len(common_grid) < MIN_POINTS_REQUIRED:
            continue

        arrs = []
        for curve in members:
            interp_y = interpolateCurveToGrid(curve['voltage'], curve[metric_key], common_grid)
            if interp_y is not None:
                arrs.append(interp_y)

        if len(arrs) == 0:
            continue

        arrs = np.vstack(arrs)
        results[key] = {
            'voltage': common_grid,
            'mean': np.nanmean(arrs, axis=0),
            'std': np.nanstd(arrs, axis=0),
            'n': arrs.shape[0],
            'members': members,
        }

    return results


# =========================================================
# PLOTS
# =========================================================

def plot_avg_raw_cv(grouped_raw, dataset_cfgs):
    labels = [dataset_label_from_config(cfg) for cfg in dataset_cfgs]
    folder_colors = get_folder_colors(labels)

    fig, ax = plt.subplots(figsize=(10, 6))
    yscale_xy_pairs = []

    for cfg in dataset_cfgs:
        label = dataset_label_from_config(cfg)
        color = folder_colors[label]

        for direction in ['PN', 'NP']:
            key = (label, direction)
            if key not in grouped_raw:
                continue

            item = grouped_raw[key]
            x = np.asarray(item['voltage'], dtype=float)
            y = np.asarray(item['mean'], dtype=float)
            ystd = np.asarray(item['std'], dtype=float)

            ax.plot(
                x, y,
                color=color,
                marker=DIRECTION_MARKERS[direction],
                linestyle=DIRECTION_LINESTYLES[direction],
                markersize=3,
                linewidth=2,
            )
            ax.fill_between(
                x,
                y - ystd,
                y + ystd,
                color=color, alpha=0.10
            )

            yscale_xy_pairs.append((x, y))
            yscale_xy_pairs.append((x, y - ystd))
            yscale_xy_pairs.append((x, y + ystd))

    ax.set_xlabel('Voltage (V)')
    ax.set_ylabel('Capacitance (F)')
    ax.set_title(f'Averaged Raw C-V Comparison - {TARGET_FREQUENCY}, {comparison_size_label(dataset_cfgs)}')
    if CV_USE_XLIM:
        ax.set_xlim(CV_XMIN, CV_XMAX)
    _manual_or_auto_ylim_from_visible_x(
        ax,
        yscale_xy_pairs,
        use_manual_ylim=CV_USE_YLIM,
        ymin=CV_YMIN,
        ymax=CV_YMAX,
        auto_ylim_to_xlim=CV_AUTO_YLIM_TO_XLIM,
        padding_fraction=CV_Y_PADDING_FRACTION,
    )
    ax.grid(True)
    add_comparison_legends(ax, folder_colors, include_curve_type=False)
    show_plot(fig)


def plot_avg_and_corrected_cv(grouped_raw, grouped_corr, dataset_cfgs):
    labels = [dataset_label_from_config(cfg) for cfg in dataset_cfgs]
    folder_colors = get_folder_colors(labels)

    fig, ax = plt.subplots(figsize=(11, 6))
    yscale_xy_pairs = []

    for cfg in dataset_cfgs:
        label = dataset_label_from_config(cfg)
        color = folder_colors[label]

        for direction in ['PN', 'NP']:
            key = (label, direction)

            if key in grouped_raw:
                item = grouped_raw[key]
                x = np.asarray(item['voltage'], dtype=float)
                y = np.asarray(item['mean'], dtype=float)

                ax.plot(
                    x, y,
                    color=color,
                    marker=DIRECTION_MARKERS[direction],
                    linestyle=':',
                    markersize=2,
                    linewidth=RAW_LINEWIDTH,
                    alpha=RAW_ALPHA,
                )
                yscale_xy_pairs.append((x, y))

            if key in grouped_corr:
                item = grouped_corr[key]
                x = np.asarray(item['voltage'], dtype=float)
                y = np.asarray(item['mean'], dtype=float)
                corr_ls = 'solid' if direction == 'PN' else 'dashdot'
                ax.plot(
                    x, y,
                    color=color,
                    marker=DIRECTION_MARKERS[direction],
                    linestyle=corr_ls,
                    markersize=4,
                    linewidth=CORRECTED_LINEWIDTH,
                    alpha=CORRECTED_ALPHA,
                )
                yscale_xy_pairs.append((x, y))

    ax.set_xlabel('Voltage (V)')
    ax.set_ylabel('Capacitance (F)')
    ax.set_title(f'Averaged Raw + Corrected C-V Comparison - {TARGET_FREQUENCY}, {comparison_size_label(dataset_cfgs)}')
    if CV_USE_XLIM:
        ax.set_xlim(CV_XMIN, CV_XMAX)
    _manual_or_auto_ylim_from_visible_x(
        ax,
        yscale_xy_pairs,
        use_manual_ylim=CV_USE_YLIM,
        ymin=CV_YMIN,
        ymax=CV_YMAX,
        auto_ylim_to_xlim=CV_AUTO_YLIM_TO_XLIM,
        padding_fraction=CV_Y_PADDING_FRACTION,
    )
    ax.grid(True)
    add_comparison_legends(ax, folder_colors, include_curve_type=True)
    show_plot(fig)


def plot_combined_corrected_cv_and_inverse_c2(grouped_corr, grouped_inv_c2, dataset_cfgs):
    """
    Plot corrected capacitance and 1/C^2 against the same voltage axis.

    Corrected capacitance uses the left y-axis, while 1/C^2 and its linear
    doping fit use the right y-axis. Each y-axis label, ticks, spine, and
    corresponding curves share the same color so the association is clear.
    """
    fig, ax_c = plt.subplots(figsize=COMBINED_FIGSIZE)
    ax_inv = ax_c.twinx()

    c_xy_pairs = []
    inv_xy_pairs = []
    curve_handles = []

    # The same voltage interval is used for the fit and concentration extraction.
    ax_c.axvspan(
        DOPING_FIT_VMIN,
        DOPING_FIT_VMAX,
        color=COMBINED_FIT_REGION_COLOR,
        alpha=COMBINED_FIT_REGION_ALPHA,
        zorder=0,
    )

    for cfg_index, cfg in enumerate(dataset_cfgs):
        label = dataset_label_from_config(cfg)
        area_mm2 = cfg.get('area_mm2', np.nan)

        # Slightly reduce alpha for later datasets while preserving the
        # metric-specific axis colors.
        dataset_alpha = max(0.45, 1.0 - 0.12 * cfg_index)

        for direction in ['PN', 'NP']:
            key = (label, direction)
            marker = DIRECTION_MARKERS[direction]
            linestyle = DIRECTION_LINESTYLES[direction]

            if key in grouped_corr:
                item_c = grouped_corr[key]
                x_c = np.asarray(item_c['voltage'], dtype=float)
                y_c = np.asarray(item_c['mean'], dtype=float)

                ax_c.plot(
                    x_c,
                    y_c,
                    color=COMBINED_C_AXIS_COLOR,
                    marker=marker,
                    linestyle=linestyle,
                    markersize=3,
                    linewidth=CORRECTED_LINEWIDTH,
                    alpha=dataset_alpha,
                    zorder=3,
                )
                c_xy_pairs.append((x_c, y_c))

                curve_handles.append(
                    Line2D(
                        [0], [0],
                        color=COMBINED_C_AXIS_COLOR,
                        marker=marker,
                        linestyle=linestyle,
                        linewidth=CORRECTED_LINEWIDTH,
                        markersize=6,
                        alpha=dataset_alpha,
                        label=f'{label} - {direction} - corrected C',
                    )
                )

            if key not in grouped_inv_c2:
                continue

            item_inv = grouped_inv_c2[key]
            x_inv = np.asarray(item_inv['voltage'], dtype=float)
            y_inv = np.asarray(item_inv['mean'], dtype=float)

            ax_inv.plot(
                x_inv,
                y_inv,
                color=COMBINED_INVC2_AXIS_COLOR,
                marker=marker,
                linestyle=linestyle,
                markersize=3,
                linewidth=2,
                alpha=dataset_alpha,
                zorder=4,
            )
            inv_xy_pairs.append((x_inv, y_inv))

            curve_handles.append(
                Line2D(
                    [0], [0],
                    color=COMBINED_INVC2_AXIS_COLOR,
                    marker=marker,
                    linestyle=linestyle,
                    linewidth=2,
                    markersize=6,
                    alpha=dataset_alpha,
                    label=f'{label} - {direction} - 1/C²',
                )
            )

            fit = fit_inverse_c2_line(
                item_inv['voltage'],
                item_inv['mean'],
                area_mm2,
                DOPING_FIT_VMIN,
                DOPING_FIT_VMAX,
            )

            if COMBINED_SHOW_BEST_FIT_LINE and np.isfinite(fit['slope']):
                ax_inv.plot(
                    fit['x_line'],
                    fit['y_line'],
                    color=COMBINED_INVC2_AXIS_COLOR,
                    linestyle=linestyle,
                    linewidth=3.2,
                    alpha=dataset_alpha,
                    zorder=5,
                )
                inv_xy_pairs.append((fit['x_line'], fit['y_line']))

                if COMBINED_LABEL_DOPING_FIT_LINES and LABEL_DOPING_FIT_LINES:
                    fit_label = format_doping_fit_label(fit)
                    if fit_label is not None and len(fit['x_line']) > 0:
                        fraction = np.clip(DOPING_FIT_LABEL_X_FRACTION, 0.0, 1.0)
                        label_index = int(round(fraction * (len(fit['x_line']) - 1)))
                        label_x = fit['x_line'][label_index]
                        label_y = fit['y_line'][label_index]

                        y_offset = 10 if direction == 'PN' else -10
                        vertical_alignment = 'bottom' if direction == 'PN' else 'top'

                        ax_inv.annotate(
                            fit_label,
                            xy=(label_x, label_y),
                            xytext=(6, y_offset),
                            textcoords='offset points',
                            color=COMBINED_INVC2_AXIS_COLOR,
                            fontsize=DOPING_FIT_LABEL_FONTSIZE,
                            ha='left',
                            va=vertical_alignment,
                            bbox=dict(
                                boxstyle='round,pad=0.25',
                                facecolor='white',
                                edgecolor=COMBINED_INVC2_AXIS_COLOR,
                                alpha=0.85,
                            ),
                            zorder=6,
                        )

    ax_c.set_xlabel('Voltage (V)')
    ax_c.set_ylabel('Corrected capacitance (F)', color=COMBINED_C_AXIS_COLOR)
    ax_inv.set_ylabel('1 / C² (1/F²)', color=COMBINED_INVC2_AXIS_COLOR)

    # Match each y-axis styling to its corresponding curve family.
    ax_c.tick_params(axis='y', colors=COMBINED_C_AXIS_COLOR)
    ax_inv.tick_params(axis='y', colors=COMBINED_INVC2_AXIS_COLOR)
    ax_c.spines['left'].set_color(COMBINED_C_AXIS_COLOR)
    ax_inv.spines['right'].set_color(COMBINED_INVC2_AXIS_COLOR)
    ax_c.yaxis.get_offset_text().set_color(COMBINED_C_AXIS_COLOR)
    ax_inv.yaxis.get_offset_text().set_color(COMBINED_INVC2_AXIS_COLOR)

    source_label = 'corrected C' if DOPING_USE_CORRECTED_CAP else 'raw C'
    ax_c.set_title(
        f'Corrected C and 1/C² vs V - {TARGET_FREQUENCY}, '
        f'{comparison_size_label(dataset_cfgs)} (doping fit uses {source_label})'
    )

    if CV_USE_XLIM:
        ax_c.set_xlim(CV_XMIN, CV_XMAX)

    _manual_or_auto_ylim_from_visible_x(
        ax_c,
        c_xy_pairs,
        use_manual_ylim=CV_USE_YLIM,
        ymin=CV_YMIN,
        ymax=CV_YMAX,
        auto_ylim_to_xlim=CV_AUTO_YLIM_TO_XLIM,
        padding_fraction=CV_Y_PADDING_FRACTION,
    )
    _manual_or_auto_ylim_from_visible_x(
        ax_inv,
        inv_xy_pairs,
        use_manual_ylim=INVC2_USE_YLIM,
        ymin=INVC2_YMIN,
        ymax=INVC2_YMAX,
        auto_ylim_to_xlim=INVC2_AUTO_YLIM_TO_XLIM,
        padding_fraction=INVC2_Y_PADDING_FRACTION,
    )

    ax_inv.ticklabel_format(axis='y', style='sci', scilimits=(0, 0))
    ax_c.grid(True, axis='both')

    legend_handles = curve_handles + [
        Patch(
            facecolor=COMBINED_FIT_REGION_COLOR,
            edgecolor='none',
            alpha=COMBINED_FIT_REGION_ALPHA,
            label=(
                f'Doping-fit region '
                f'({DOPING_FIT_VMIN:g} to {DOPING_FIT_VMAX:g} V)'
            ),
        )
    ]
    if COMBINED_SHOW_BEST_FIT_LINE:
        legend_handles.append(
            Line2D(
                [0], [0],
                color=COMBINED_INVC2_AXIS_COLOR,
                linewidth=3.2,
                label='1/C² linear best fit',
            )
        )

    if legend_handles:
        ax_c.legend(handles=legend_handles, loc='best', fontsize=8)

    show_plot(fig)


def plot_avg_inverse_c2_with_fit(grouped_inv_c2, dataset_cfgs):
    labels = [dataset_label_from_config(cfg) for cfg in dataset_cfgs]
    folder_colors = get_folder_colors(labels)

    fig, ax = plt.subplots(figsize=(11, 6))
    yscale_xy_pairs = []
    ax.axvspan(DOPING_FIT_VMIN, DOPING_FIT_VMAX, alpha=0.08)

    for cfg in dataset_cfgs:
        label = dataset_label_from_config(cfg)
        color = folder_colors[label]
        area_mm2 = cfg.get('area_mm2', np.nan)

        for direction in ['PN', 'NP']:
            key = (label, direction)
            if key not in grouped_inv_c2:
                continue

            item = grouped_inv_c2[key]
            x = np.asarray(item['voltage'], dtype=float)
            y = np.asarray(item['mean'], dtype=float)

            ax.plot(
                x, y,
                color=color,
                marker=DIRECTION_MARKERS[direction],
                linestyle=DIRECTION_LINESTYLES[direction],
                markersize=3,
                linewidth=2,
            )
            yscale_xy_pairs.append((x, y))

            fit = fit_inverse_c2_line(
                item['voltage'],
                item['mean'],
                area_mm2,
                DOPING_FIT_VMIN,
                DOPING_FIT_VMAX
            )

            if np.isfinite(fit['slope']):
                fit_ls = 'solid' if direction == 'PN' else 'dashdot'
                ax.plot(
                    fit['x_line'],
                    fit['y_line'],
                    color=color,
                    linestyle=fit_ls,
                    linewidth=3,
                    alpha=0.9
                )
                yscale_xy_pairs.append((fit['x_line'], fit['y_line']))

                if LABEL_DOPING_FIT_LINES:
                    fit_label = format_doping_fit_label(fit)
                    if fit_label is not None and len(fit['x_line']) > 0:
                        fraction = np.clip(DOPING_FIT_LABEL_X_FRACTION, 0.0, 1.0)
                        label_index = int(round(fraction * (len(fit['x_line']) - 1)))
                        label_x = fit['x_line'][label_index]
                        label_y = fit['y_line'][label_index]

                        # Offset PN and NP labels in opposite directions to reduce overlap.
                        y_offset = 10 if direction == 'PN' else -10
                        vertical_alignment = 'bottom' if direction == 'PN' else 'top'

                        ax.annotate(
                            fit_label,
                            xy=(label_x, label_y),
                            xytext=(6, y_offset),
                            textcoords='offset points',
                            color=color,
                            fontsize=DOPING_FIT_LABEL_FONTSIZE,
                            ha='left',
                            va=vertical_alignment,
                            bbox=dict(
                                boxstyle='round,pad=0.25',
                                facecolor='white',
                                edgecolor=color,
                                alpha=0.85,
                            ),
                        )

    ylabel = '1 / C² (1/F²)'
    source_label = 'corrected C' if DOPING_USE_CORRECTED_CAP else 'raw C'

    ax.set_xlabel('Voltage (V)')
    ax.set_ylabel(ylabel)
    ax.set_title(
        f'1/C² vs V for Doping Extraction - {TARGET_FREQUENCY}, '
        f'{comparison_size_label(dataset_cfgs)} ({source_label})'
    )
    if CV_USE_XLIM:
        ax.set_xlim(CV_XMIN, CV_XMAX)
    _manual_or_auto_ylim_from_visible_x(
        ax,
        yscale_xy_pairs,
        use_manual_ylim=INVC2_USE_YLIM,
        ymin=INVC2_YMIN,
        ymax=INVC2_YMAX,
        auto_ylim_to_xlim=INVC2_AUTO_YLIM_TO_XLIM,
        padding_fraction=INVC2_Y_PADDING_FRACTION,
    )
    ax.ticklabel_format(axis='y', style='sci', scilimits=(0, 0))
    ax.grid(True)
    add_comparison_legends(ax, folder_colors, include_curve_type=False)
    show_plot(fig)


# =========================================================
# SUMMARY
# =========================================================

def build_doping_summary(grouped_inv_c2, dataset_cfgs):
    rows = []

    for cfg in dataset_cfgs:
        label = dataset_label_from_config(cfg)
        area_mm2 = cfg.get('area_mm2', np.nan)

        row = {
            'folder': label,
            'size': cfg.get('size_to_compare', ''),
            'area_mm2': area_mm2,
            'frequency': TARGET_FREQUENCY,
            'fit_Vmin': DOPING_FIT_VMIN,
            'fit_Vmax': DOPING_FIT_VMAX,
            'cap_used': 'corrected' if DOPING_USE_CORRECTED_CAP else 'raw',
        }

        doping_vals = []
        type_vals = []

        for direction in ['PN', 'NP']:
            key = (label, direction)

            if key not in grouped_inv_c2:
                row[f'npts_fit_{direction}'] = 0
                row[f'slope_{direction}'] = np.nan
                row[f'R2_{direction}'] = np.nan
                row[f'type_{direction}'] = ''
                row[f'N_{direction}_cm^-3'] = np.nan
                continue

            item = grouped_inv_c2[key]
            fit = fit_inverse_c2_line(
                item['voltage'],
                item['mean'],
                area_mm2,
                DOPING_FIT_VMIN,
                DOPING_FIT_VMAX
            )

            row[f'npts_fit_{direction}'] = fit['npts']
            row[f'slope_{direction}'] = fit['slope']
            row[f'R2_{direction}'] = fit['r2']
            row[f'type_{direction}'] = fit['carrier_type']
            row[f'N_{direction}_cm^-3'] = fit['doping_cm3_abs']

            if np.isfinite(fit['doping_cm3_abs']):
                doping_vals.append(fit['doping_cm3_abs'])
            if fit['carrier_type'] != 'unknown':
                type_vals.append(fit['carrier_type'])

        row['N_mean_cm^-3'] = np.nanmean(doping_vals) if len(doping_vals) else np.nan

        unique_types = list(dict.fromkeys(type_vals))
        if len(unique_types) == 1:
            row['type_consensus'] = unique_types[0]
        elif len(unique_types) > 1:
            row['type_consensus'] = 'mixed / check fit window'
        else:
            row['type_consensus'] = 'unknown'

        rows.append(row)

    summary = pd.DataFrame(rows)

    display_cols = [
        'folder',
        'size',
        'area_mm2',
        'frequency',
        'cap_used',
        'fit_Vmin',
        'fit_Vmax',
        'npts_fit_PN',
        'slope_PN',
        'R2_PN',
        'type_PN',
        'N_PN_cm^-3',
        'npts_fit_NP',
        'slope_NP',
        'R2_NP',
        'type_NP',
        'N_NP_cm^-3',
        'type_consensus',
        'N_mean_cm^-3',
    ]
    display_cols = [c for c in display_cols if c in summary.columns]
    summary_display = summary[display_cols].copy()

    print('\nDoping extraction summary:')
    print(summary_display.to_string(index=False))

    fig_width = max(18, 0.9 * len(summary_display.columns))
    fig_height = max(3.0, 1.0 + 0.35 * len(summary_display))
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    ax.axis('off')

    disp = summary_display.copy()
    for col in disp.columns:
        if col in ['folder', 'size', 'frequency', 'cap_used', 'type_PN', 'type_NP', 'type_consensus']:
            continue
        disp[col] = disp[col].apply(lambda x: f'{x:.4g}' if pd.notnull(x) and np.isfinite(x) else '')

    tbl = ax.table(
        cellText=disp.values,
        colLabels=disp.columns,
        loc='center'
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(8)
    tbl.scale(1, 1.35)
    show_plot(fig)

    return summary


# =========================================================
# MAIN
# =========================================================

def validate_datasets(dataset_cfgs):
    if len(dataset_cfgs) == 0:
        raise ValueError('DATASETS is empty.')

    labels = [dataset_label_from_config(cfg) for cfg in dataset_cfgs]
    if len(labels) != len(set(labels)):
        raise ValueError('Dataset labels must be unique. Change the label field or folder names.')

    for cfg in dataset_cfgs:
        if 'folder' not in cfg:
            raise ValueError('Each dataset config needs a folder key.')
        if 'size_to_compare' not in cfg:
            raise ValueError('Each dataset config needs a size_to_compare key.')
        if cfg['size_to_compare'] not in ['Small', 'Medium', 'Large']:
            raise ValueError(f"Unsupported size_to_compare: {cfg['size_to_compare']}")
        if 'area_mm2' not in cfg:
            raise ValueError('Each dataset config needs area_mm2 for doping extraction.')
        if not np.isfinite(cfg['area_mm2']) or cfg['area_mm2'] <= 0:
            raise ValueError('area_mm2 must be finite and > 0 for doping extraction.')


def main():
    validate_datasets(DATASETS)

    all_curves = []
    for cfg in DATASETS:
        curves = collect_curves_for_dataset(cfg)
        all_curves.extend(curves)
        print(f'Collected {len(curves)} usable curves from {dataset_label_from_config(cfg)}')

    if len(all_curves) == 0:
        print('No usable curves were found.')
        return

    grouped_raw = group_curves(all_curves, 'capacitance', ['dataset_label', 'direction'])
    grouped_corr = group_curves(all_curves, 'capacitance_corrected', ['dataset_label', 'direction'])

    inv_metric = 'inverse_c2_corrected' if DOPING_USE_CORRECTED_CAP else 'inverse_c2'
    grouped_inv_c2 = group_curves(all_curves, inv_metric, ['dataset_label', 'direction'])

    plot_avg_raw_cv(grouped_raw, DATASETS)
    plot_avg_and_corrected_cv(grouped_raw, grouped_corr, DATASETS)
    plot_avg_inverse_c2_with_fit(grouped_inv_c2, DATASETS)
    if PLOT_COMBINED_CORRECTED_C_AND_INVC2:
        plot_combined_corrected_cv_and_inverse_c2(
            grouped_corr, grouped_inv_c2, DATASETS
        )
    build_doping_summary(grouped_inv_c2, DATASETS)

    print('\nDone.')
    print('\nNotes:')
    print('- Doping is extracted from the fitted slope of 1/C^2 vs V.')
    print('- Positive slope implies acceptors (p-type); negative slope implies donors (n-type).')
    print('- Adjust DOPING_FIT_VMIN and DOPING_FIT_VMAX so the fit covers only the linear depletion region.')
    print('- Compare PN and NP results; if they disagree, trust the cleaner linear fit / higher R^2.')

if __name__ == '__main__':
    main()

from google.colab import drive
drive.mount('/content/drive')