# -*- coding: utf-8 -*-
"""General doping modeler vibe code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UgiMLBF79tA7txb09nFoFGAxeO46VgXj
"""

# general_diffusion_profile_simulator_toggle_engine_updated.py
#
# General 1D dopant diffusion simulator for silicon.
#
# Features:
#   - Choose background dopant type and concentration
#   - Compare multiple independently defined diffusion processes on one plot
#   - Program an arbitrary number of diffusion steps within each process
#   - Each step can be:
#       * predep  (source_dopant = "boron" or "phosphorus")
#       * drive-in (source_dopant = None)
#   - One comparison plot containing the final profiles from every process
#   - Can use either:
#       * analytic engine: rigid erfc predep + Gaussian redistribution
#       * numeric engine: implicit finite-difference solver
#   - Calculates final Rs from:
#       * x = 0 to x = xj if a junction exists
#       * x = 0 to wafer thickness if no junction exists
#   - Background is part of the initial condition, so same-type diffusion
#     naturally gives one total species curve that relaxes toward the background
#
# Notes:
#   - Analytic mode assumes a semi-infinite substrate and uses erfc/Gaussian
#     as an engineering superposition model across multiple steps.
#   - Numeric mode uses a finite wafer thickness and zero-flux backside boundary.
#   - One source dopant per step (or no source).

import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnchoredText

# ============================================================
# USER INPUTS
# ============================================================

# Toggle:
#   "analytic" -> rigidly use erfc for predep and Gaussian for later redistribution
#   "numeric"  -> implicit finite-difference solver
DIFFUSION_ENGINE = "analytic"

# Background wafer doping
BACKGROUND_DOPANT = "boron"          # "boron" or "phosphorus"
BACKGROUND_CONCENTRATION_CM3 = 2.0e15

# Wafer thickness:
#   1) full simulation depth in numeric mode
#   2) Rs integration depth if no junction exists
#   3) max x-grid depth in both modes
WAFER_THICKNESS_UM = 525.0

# Diffusion processes to compare on the same plot.
#
# Each item in PROCESSES is simulated independently from the same background
# wafer. Add or remove process dictionaries as needed. Each process may contain
# any number of predeposition and drive-in steps.
#
# source_dopant:
#   - "boron" or "phosphorus" => predep for that species during that step
#   - None                    => no source present (drive-in for all existing dopants)
PROCESSES = [
    {
        "name": "Stronger predep (800C 5min) with 1100C 60 min drive in",
        "steps": [
            {
                "name": "Phosphorus predep",
                "temp_C": 800.0,
                "time_min": 5.0,
                "source_dopant": "phosphorus",
                "surface_concentration_cm3": 1.0e20,
            },
            {
                "name": "drive in",
                "temp_C": 1100.0,
                "time_min": 60.0,
                "source_dopant": None,
                "surface_concentration_cm3": None,
            },
            {
                "name": "Boron predep",
                "temp_C": 1000.0,
                "time_min": 5.0,
                "source_dopant": "boron",
                "surface_concentration_cm3": 2e20,
            },
        ],
    },

]


# Plot/grid controls
# Numeric mode uses a uniform grid.
NUM_POINTS_UNIFORM = 1800

# Analytic mode uses a dense near-surface grid plus a coarser deep grid.
NUM_FINE_POINTS = 5000
NUM_COARSE_POINTS = 1200
FINE_REGION_UM = 25.0

PLOT_XMAX_UM = 2.5
USE_LOG_Y = True

# Set to None for auto-limits
YMIN_CM3 = 1e14
YMAX_CM3 = 5e20

# Show faint cumulative step profiles
SHOW_INTERMEDIATE_STEPS = True

# Plot a lower-right summary of the programmed diffusion steps and
# the Arrhenius diffusion constants used for phosphorus and boron.
SHOW_PROCESS_SUMMARY_BOX = True
PROCESS_SUMMARY_FONT_SIZE = 8

PLOT_TITLE = "CMOS - Predicted PMOS source/drain dopant profile"

# ============================================================
# ELECTRICAL MODEL SETTINGS
# ============================================================

# Set to False to hide the expected sheet-resistance value from both
# the terminal summary and the plot annotation. Rs is still calculated
# internally, so it can be re-enabled without changing the model.
SHOW_RS = False

ACTIVATION_PHOSPHORUS = 1.0
ACTIVATION_BORON = 1.0

MOBILITY_MODEL = "caughey_thomas"   # "caughey_thomas" or "constant"

# Used only if MOBILITY_MODEL == "constant"
MU_N_CONST_CM2_VS = 300.0
MU_P_CONST_CM2_VS = 150.0

CT_PARAMS = {
    "n": {"mu_min": 52.2, "mu_max": 1417.0, "Nref": 9.68e16, "alpha": 0.68},
    "p": {"mu_min": 44.9, "mu_max": 470.5,  "Nref": 2.23e17, "alpha": 0.70},
}

# ============================================================
# DIFFUSION DATABASE
# ============================================================

DOPANT_DATABASE = {
    "phosphorus": {"D0_cm2_per_s": 3.72E-4, "Ea_eV": 2.5, "type": "donor"},
    "boron": {"D0_cm2_per_s": .76, "Ea_eV": 3.46, "type": "acceptor"},
}

K_B_EV_PER_K = 8.617333262145e-5
Q_E = 1.602176634e-19

COLOR_BORON = "tab:blue"
COLOR_PHOSPHORUS = "tab:orange"
COLOR_JUNCTION = "black"

# Dopant identity is shown by color; process identity is shown by line style.
# Styles repeat if more processes are added than entries listed here.
PROCESS_LINESTYLES = ["-", "--", "-.", ":"]

# ============================================================
# BASIC HELPERS
# ============================================================

def diffusivity_cm2_s(dopant_name, T_C):
    dop = DOPANT_DATABASE[dopant_name.lower()]
    D0 = dop["D0_cm2_per_s"]
    Ea = dop["Ea_eV"]
    T_K = T_C + 273.15
    return D0 * np.exp(-Ea / (K_B_EV_PER_K * T_K))

def erfc_array(x):
    return np.vectorize(math.erfc)(x)

def predep_erfc_profile_cm3(x_cm, Cs_cm3, D_cm2_s, t_s):
    if D_cm2_s <= 0 or t_s <= 0:
        return np.zeros_like(x_cm)
    return Cs_cm3 * erfc_array(x_cm / (2.0 * np.sqrt(D_cm2_s * t_s)))

def gaussian_from_predep_cm3(x_cm, Cs_pre_cm3, D_pre_cm2_s, t_pre_s, L_drive_cm2):
    """
    Convert one earlier predep into a Gaussian after later redistribution.

    Q = 2 * Cs * sqrt(D_pre * t_pre / pi)

    C(x) = Q / sqrt(pi * L_drive) * exp(-x^2 / (4 L_drive))
    """
    if D_pre_cm2_s <= 0 or t_pre_s <= 0 or L_drive_cm2 <= 0:
        return np.zeros_like(x_cm)

    Q = 2.0 * Cs_pre_cm3 * np.sqrt(D_pre_cm2_s * t_pre_s / np.pi)
    return (Q / np.sqrt(np.pi * L_drive_cm2)) * np.exp(-(x_cm ** 2) / (4.0 * L_drive_cm2))

def format_sci(val, digits=3):
    if val is None:
        return "None"
    return f"{val:.{digits}e}"

def integrate_to_depth(x_cm, y, x_end_cm):
    if x_end_cm is None:
        return None

    if x_end_cm <= x_cm[0]:
        return 0.0

    if x_end_cm >= x_cm[-1]:
        return np.trapz(y, x_cm)

    i = np.searchsorted(x_cm, x_end_cm)

    x_part = np.concatenate([x_cm[:i], [x_end_cm]])
    y_end = np.interp(x_end_cm, x_cm, y)
    y_part = np.concatenate([y[:i], [y_end]])

    return np.trapz(y_part, x_part)

def first_junction_depth_cm(x_cm, ND_cm3, NA_cm3):
    """
    Finds first depth where net doping changes sign.
    Returns:
      xj_cm
      surface_polarity = "n", "p", or None
    """
    net = np.asarray(ND_cm3) - np.asarray(NA_cm3)

    if net[0] > 0:
        polarity = "n"
        idx = np.where(net <= 0)[0]
    elif net[0] < 0:
        polarity = "p"
        idx = np.where(net >= 0)[0]
    else:
        nz = np.where(np.abs(net) > 0)[0]
        if len(nz) == 0:
            return None, None
        if net[nz[0]] > 0:
            polarity = "n"
            idx = np.where(net <= 0)[0]
        else:
            polarity = "p"
            idx = np.where(net >= 0)[0]

    if len(idx) == 0:
        return None, polarity

    i = idx[0]
    if i == 0:
        return x_cm[0], polarity

    x1, x2 = x_cm[i - 1], x_cm[i]
    y1, y2 = net[i - 1], net[i]
    if y2 == y1:
        return x1, polarity

    xj = x1 + (0.0 - y1) * (x2 - x1) / (y2 - y1)
    return xj, polarity

def mobility_cm2_Vs(total_ionized_cm3, carrier_type):
    N = np.maximum(np.asarray(total_ionized_cm3, dtype=float), 1.0)

    if MOBILITY_MODEL == "constant":
        if carrier_type == "n":
            return np.full_like(N, MU_N_CONST_CM2_VS)
        return np.full_like(N, MU_P_CONST_CM2_VS)

    if MOBILITY_MODEL == "caughey_thomas":
        p = CT_PARAMS[carrier_type]
        return p["mu_min"] + (p["mu_max"] - p["mu_min"]) / (1.0 + (N / p["Nref"]) ** p["alpha"])

    raise ValueError(f"Unknown MOBILITY_MODEL: {MOBILITY_MODEL}")

def compute_sheet_resistance(x_cm, ND_cm3, NA_cm3, x_end_cm, surface_polarity):
    if x_end_cm is None or surface_polarity is None:
        return None, None, None, None

    ND = np.asarray(ND_cm3, dtype=float)
    NA = np.asarray(NA_cm3, dtype=float)
    total_ionized = ND + NA

    if surface_polarity == "n":
        majority = np.maximum(ND - NA, 0.0)
        mu = mobility_cm2_Vs(total_ionized, "n")
    else:
        majority = np.maximum(NA - ND, 0.0)
        mu = mobility_cm2_Vs(total_ionized, "p")

    sigma = Q_E * mu * majority
    Gsheet = integrate_to_depth(x_cm, sigma, x_end_cm)
    carrier_dose = integrate_to_depth(x_cm, majority, x_end_cm)

    if Gsheet is None or Gsheet <= 0:
        return None, Gsheet, carrier_dose, None

    Rs = 1.0 / Gsheet
    mu_eff = Gsheet / (Q_E * carrier_dose) if carrier_dose is not None and carrier_dose > 0 else None
    return Rs, Gsheet, carrier_dose, mu_eff

# ============================================================
# GRID HELPERS
# ============================================================

def make_x_grid(engine, wafer_thickness_um):
    """
    Analytic mode:
      dense near-surface grid + coarser deep grid
    Numeric mode:
      uniform grid (required by the FD solver)
    """
    if engine == "analytic":
        fine_um = min(FINE_REGION_UM, wafer_thickness_um)

        if fine_um >= wafer_thickness_um:
            x_um = np.linspace(0.0, wafer_thickness_um, NUM_FINE_POINTS)
        else:
            x_fine = np.linspace(0.0, fine_um, NUM_FINE_POINTS, endpoint=False)
            x_coarse = np.linspace(fine_um, wafer_thickness_um, NUM_COARSE_POINTS)
            x_um = np.unique(np.concatenate([x_fine, x_coarse]))
    else:
        x_um = np.linspace(0.0, wafer_thickness_um, NUM_POINTS_UNIFORM)

    return x_um * 1e-4, x_um

# ============================================================
# NUMERIC ENGINE
# ============================================================

def solve_tridiagonal(a, b, c, d):
    n = len(b)
    ac = a.astype(float).copy()
    bc = b.astype(float).copy()
    cc = c.astype(float).copy()
    dc = d.astype(float).copy()

    for i in range(1, n):
        m = ac[i - 1] / bc[i - 1]
        bc[i] -= m * cc[i - 1]
        dc[i] -= m * dc[i - 1]

    x = np.zeros(n, dtype=float)
    x[-1] = dc[-1] / bc[-1]

    for i in range(n - 2, -1, -1):
        x[i] = (dc[i] - cc[i] * x[i + 1]) / bc[i]

    return x

def diffuse_one_species_implicit(profile_cm3, D_cm2_s, total_time_s, dx_cm,
                                 source_present=False, surface_concentration_cm3=None,
                                 r_target=0.5):
    C = np.asarray(profile_cm3, dtype=float).copy()
    n = C.size

    if total_time_s <= 0 or D_cm2_s <= 0:
        if source_present and surface_concentration_cm3 is not None:
            C[0] = surface_concentration_cm3
        return C

    n_sub = max(1, int(np.ceil(D_cm2_s * total_time_s / (r_target * dx_cm * dx_cm))))
    dt_s = total_time_s / n_sub
    r = D_cm2_s * dt_s / (dx_cm * dx_cm)

    a = np.zeros(n - 1, dtype=float)
    b = np.zeros(n, dtype=float)
    c = np.zeros(n - 1, dtype=float)

    if source_present:
        b[0] = 1.0
        c[0] = 0.0
    else:
        b[0] = 1.0 + 2.0 * r
        c[0] = -2.0 * r

    for i in range(1, n - 1):
        a[i - 1] = -r
        b[i] = 1.0 + 2.0 * r
        c[i] = -r

    a[-1] = -2.0 * r
    b[-1] = 1.0 + 2.0 * r

    for _ in range(n_sub):
        rhs = C.copy()
        if source_present:
            rhs[0] = surface_concentration_cm3
        C = solve_tridiagonal(a, b, c, rhs)
        C = np.maximum(C, 0.0)

    return C

def build_history_numeric(x_cm, steps, background_dopant, background_conc_cm3):
    dx_cm = x_cm[1] - x_cm[0]

    phosphorus = np.zeros_like(x_cm)
    boron = np.zeros_like(x_cm)

    if background_dopant == "boron":
        boron[:] = background_conc_cm3
    else:
        phosphorus[:] = background_conc_cm3

    history = [{
        "name": "Initial",
        "phosphorus": phosphorus.copy(),
        "boron": boron.copy(),
    }]

    for step in steps:
        temp_C = float(step["temp_C"])
        time_s = float(step["time_min"]) * 60.0
        source_dopant = step.get("source_dopant", None)
        source_conc = step.get("surface_concentration_cm3", None)

        Dp = diffusivity_cm2_s("phosphorus", temp_C)
        Db = diffusivity_cm2_s("boron", temp_C)

        phosphorus = diffuse_one_species_implicit(
            phosphorus, Dp, time_s, dx_cm,
            source_present=(source_dopant == "phosphorus"),
            surface_concentration_cm3=source_conc if source_dopant == "phosphorus" else None
        )

        boron = diffuse_one_species_implicit(
            boron, Db, time_s, dx_cm,
            source_present=(source_dopant == "boron"),
            surface_concentration_cm3=source_conc if source_dopant == "boron" else None
        )

        history.append({
            "name": step["name"],
            "phosphorus": phosphorus.copy(),
            "boron": boron.copy(),
        })

    return history

# ============================================================
# ANALYTIC ENGINE
# ============================================================

def species_profile_after_step_analytic(x_cm, species, step_end_idx, steps,
                                        background_dopant, background_conc_cm3):
    """
    Semi-infinite analytic superposition model.

    For each source-present step of this species:
      - if there is no later thermal budget up to step_end_idx:
            contribution = erfc predep
      - if there is later thermal budget:
            contribution = Gaussian redistribution of that predep dose

    All contributions are summed on top of the constant background
    if the background species matches.
    """
    total = np.zeros_like(x_cm)
    if background_dopant == species:
        total += background_conc_cm3

    for i in range(step_end_idx + 1):
        step_i = steps[i]
        if step_i.get("source_dopant", None) != species:
            continue

        T_pre = float(step_i["temp_C"])
        t_pre_s = float(step_i["time_min"]) * 60.0
        Cs = float(step_i["surface_concentration_cm3"])
        D_pre = diffusivity_cm2_s(species, T_pre)

        # cumulative later thermal budget
        L_drive = 0.0
        for k in range(i + 1, step_end_idx + 1):
            T_k = float(steps[k]["temp_C"])
            t_k_s = float(steps[k]["time_min"]) * 60.0
            D_k = diffusivity_cm2_s(species, T_k)
            L_drive += D_k * t_k_s

        if L_drive > 0:
            contrib = gaussian_from_predep_cm3(x_cm, Cs, D_pre, t_pre_s, L_drive)
        else:
            contrib = predep_erfc_profile_cm3(x_cm, Cs, D_pre, t_pre_s)

        total += contrib

    return total

def build_history_analytic(x_cm, steps, background_dopant, background_conc_cm3):
    history = []

    P0 = np.zeros_like(x_cm)
    B0 = np.zeros_like(x_cm)
    if background_dopant == "boron":
        B0[:] = background_conc_cm3
    else:
        P0[:] = background_conc_cm3

    history.append({
        "name": "Initial",
        "phosphorus": P0.copy(),
        "boron": B0.copy(),
    })

    for end_idx in range(len(steps)):
        P = species_profile_after_step_analytic(
            x_cm, "phosphorus", end_idx, steps, background_dopant, background_conc_cm3
        )
        B = species_profile_after_step_analytic(
            x_cm, "boron", end_idx, steps, background_dopant, background_conc_cm3
        )
        history.append({
            "name": steps[end_idx]["name"],
            "phosphorus": P,
            "boron": B,
        })

    return history

# ============================================================
# PLOTTING HELPERS
# ============================================================

def add_info_box(ax, lines, colors=None, loc="upper right"):
    if colors is None:
        colors = ["black"] * len(lines)

    locations = {
        "upper right": (0.98, 0.97, "right", "top", -1.0),
        "upper left": (0.02, 0.97, "left", "top", -1.0),
        "lower right": (0.98, 0.03, "right", "bottom", 1.0),
        "lower left": (0.02, 0.03, "left", "bottom", 1.0),
    }
    if loc not in locations:
        raise ValueError(f"Unsupported info-box location: {loc}")

    x0, y0, ha, va, direction = locations[loc]
    dy = 0.075

    for i, (line, color) in enumerate(zip(lines, colors)):
        ax.text(
            x0, y0 + direction * i * dy, line,
            transform=ax.transAxes,
            ha=ha, va=va,
            fontsize=9,
            color=color,
            bbox=dict(boxstyle="round,pad=0.2", fc="white", ec=color, alpha=0.88),
            zorder=10,
        )


def build_process_summary_lines(processes, background_dopant, background_conc_cm3):
    """Build compact plot text describing every compared process and constants."""
    lines = [
        "DIFFUSION STEP SUMMARY",
        f"Background: {background_dopant.title()}, {format_sci(background_conc_cm3, 2)} cm$^{{-3}}$",
    ]

    for process_index, process in enumerate(processes, start=1):
        process_name = process.get("name", f"Process {process_index}")
        steps = process.get("steps", [])
        lines.append(f"{process_index}. {process_name}")

        if not steps:
            lines.append("    No diffusion steps")
            continue

        for step_index, step in enumerate(steps, start=1):
            temp_C = float(step["temp_C"])
            time_min = float(step["time_min"])
            source = step.get("source_dopant", None)

            if source is None:
                lines.append(
                    f"    {step_index}) Drive-in: {temp_C:g} C, {time_min:g} min"
                )
            else:
                Cs = step.get("surface_concentration_cm3", None)
                source_label = "P" if source.lower() == "phosphorus" else "B"
                lines.append(
                    f"    {step_index}) {source_label} predep: {temp_C:g} C, "
                    f"{time_min:g} min, Cs={format_sci(Cs, 2)} cm$^{{-3}}$"
                )

    P = DOPANT_DATABASE["phosphorus"]
    B = DOPANT_DATABASE["boron"]
    lines.extend([
        f"P: D0={format_sci(P['D0_cm2_per_s'], 2)} cm$^2$/s, Ea={P['Ea_eV']:.2f} eV",
        f"B: D0={format_sci(B['D0_cm2_per_s'], 2)} cm$^2$/s, Ea={B['Ea_eV']:.2f} eV",
    ])
    return lines


def add_process_summary_box(ax, lines):
    """Add a left-justified multiline step-summary box in the lower-right."""
    summary_box = AnchoredText(
        "\n".join(lines),
        loc="lower right",
        prop={
            "size": PROCESS_SUMMARY_FONT_SIZE,
            "color": "black",
            "ha": "left",
            "multialignment": "left",
            "linespacing": 1.18,
        },
        frameon=True,
        borderpad=0.55,
        pad=0.45,
    )
    summary_box.patch.set_boxstyle("round,pad=0.45")
    summary_box.patch.set_facecolor("white")
    summary_box.patch.set_edgecolor("0.35")
    summary_box.patch.set_alpha(0.90)
    summary_box.set_zorder(9)
    ax.add_artist(summary_box)


def build_results_summary_lines(results):
    """Build a concise final-result summary for each process."""
    lines = ["PROCESS RESULTS"]

    for result in results:
        lines.append(result["name"])
        lines.append(
            f"  P(0)={format_sci(result['ND'][0], 2)}, "
            f"B(0)={format_sci(result['NA'][0], 2)} cm$^{{-3}}$"
        )
        if result["xj_cm"] is None:
            lines.append("  No junction found")
        else:
            lines.append(f"  xj={result['xj_cm'] * 1e4:.4f} um")

        if SHOW_RS:
            rs_text = "None" if result["Rs"] is None else f"{result['Rs']:.4g} ohm/sq"
            lines.append(f"  Rs={rs_text}")

    return lines


def add_results_summary_box(ax, lines):
    """Add a left-justified multiline results box in the upper-right."""
    box = AnchoredText(
        "\n".join(lines),
        loc="upper right",
        prop={
            "size": 7.8,
            "color": "black",
            "ha": "left",
            "multialignment": "left",
            "linespacing": 1.18,
        },
        frameon=True,
        borderpad=0.55,
        pad=0.45,
    )
    box.patch.set_boxstyle("round,pad=0.45")
    box.patch.set_facecolor("white")
    box.patch.set_edgecolor("0.35")
    box.patch.set_alpha(0.90)
    box.set_zorder(9)
    ax.add_artist(box)


def simulate_process(x_cm, engine, process, background_dopant, background_conc_cm3):
    """Simulate one independently defined diffusion process."""
    name = process.get("name", "Unnamed process")
    steps = process.get("steps", [])
    if not isinstance(steps, list) or len(steps) == 0:
        raise ValueError(f"Process '{name}' must contain at least one step")

    if engine == "analytic":
        history = build_history_analytic(
            x_cm, steps, background_dopant, background_conc_cm3
        )
    else:
        history = build_history_numeric(
            x_cm, steps, background_dopant, background_conc_cm3
        )

    final = history[-1]
    ND = ACTIVATION_PHOSPHORUS * final["phosphorus"]
    NA = ACTIVATION_BORON * final["boron"]

    xj_cm, surface_polarity = first_junction_depth_cm(x_cm, ND, NA)
    if xj_cm is None:
        x_end_cm = WAFER_THICKNESS_UM * 1e-4
        integration_basis = "wafer thickness"
    else:
        x_end_cm = xj_cm
        integration_basis = "junction depth"

    donor_dose_cm2 = integrate_to_depth(x_cm, ND, x_end_cm)
    acceptor_dose_cm2 = integrate_to_depth(x_cm, NA, x_end_cm)
    background_uniform_dose_cm2 = background_conc_cm3 * x_end_cm

    Rs, Gsheet, carrier_dose, mu_eff = compute_sheet_resistance(
        x_cm, ND, NA, x_end_cm, surface_polarity
    )

    return {
        "name": name,
        "steps": steps,
        "history": history,
        "ND": ND,
        "NA": NA,
        "xj_cm": xj_cm,
        "surface_polarity": surface_polarity,
        "x_end_cm": x_end_cm,
        "integration_basis": integration_basis,
        "donor_dose_cm2": donor_dose_cm2,
        "acceptor_dose_cm2": acceptor_dose_cm2,
        "background_uniform_dose_cm2": background_uniform_dose_cm2,
        "Rs": Rs,
        "Gsheet": Gsheet,
        "carrier_dose": carrier_dose,
        "mu_eff": mu_eff,
    }

def plot_profile(ax, x_um, y_cm3, label, color, alpha=1.0, linestyle="-", linewidth=2.0):
    if USE_LOG_Y:
        line, = ax.semilogy(
            x_um, y_cm3,
            label=label,
            color=color,
            alpha=alpha,
            linestyle=linestyle,
            linewidth=linewidth
        )
    else:
        line, = ax.plot(
            x_um, y_cm3,
            label=label,
            color=color,
            alpha=alpha,
            linestyle=linestyle,
            linewidth=linewidth
        )
    return line

def apply_axis_limits(ax):
    ax.set_xlim(0.0, PLOT_XMAX_UM)
    if YMIN_CM3 is not None or YMAX_CM3 is not None:
        ax.set_ylim(bottom=YMIN_CM3, top=YMAX_CM3)

# ============================================================
# MAIN
# ============================================================

def main():
    bg = BACKGROUND_DOPANT.strip().lower()
    if bg not in ("boron", "phosphorus"):
        raise ValueError("BACKGROUND_DOPANT must be 'boron' or 'phosphorus'")

    engine = DIFFUSION_ENGINE.strip().lower()
    if engine not in ("analytic", "numeric"):
        raise ValueError("DIFFUSION_ENGINE must be 'analytic' or 'numeric'")

    if not isinstance(PROCESSES, list) or len(PROCESSES) == 0:
        raise ValueError("PROCESSES must contain at least one process dictionary")

    x_cm, x_um = make_x_grid(engine, WAFER_THICKNESS_UM)
    results = [
        simulate_process(
            x_cm,
            engine,
            process,
            bg,
            BACKGROUND_CONCENTRATION_CM3,
        )
        for process in PROCESSES
    ]

    print("\n" + "=" * 88)
    print("DIFFUSION PROCESS COMPARISON SUMMARY")
    print("=" * 88)
    print(f"Background dopant                         : {BACKGROUND_DOPANT}")
    print(f"Background concentration                  : {format_sci(BACKGROUND_CONCENTRATION_CM3)} cm^-3")
    print(f"Wafer thickness                           : {WAFER_THICKNESS_UM:.3f} um")
    print(f"Number of compared processes              : {len(results)}")

    for process_index, result in enumerate(results, start=1):
        print("\n" + "-" * 88)
        print(f"PROCESS {process_index}: {result['name']}")
        print("-" * 88)
        print(f"Number of programmed steps                : {len(result['steps'])}")

        print("\nProgrammed steps")
        for step_index, step in enumerate(result["steps"], start=1):
            source = step.get("source_dopant", None)
            if source is None:
                print(
                    f"  {step_index}. {step['name']}: drive-in, "
                    f"T={step['temp_C']} C, t={step['time_min']} min"
                )
            else:
                print(
                    f"  {step_index}. {step['name']}: {source} predep, "
                    f"Cs={format_sci(step['surface_concentration_cm3'])} cm^-3, "
                    f"T={step['temp_C']} C, t={step['time_min']} min"
                )

        print("\nFinal surface concentrations")
        print(f"  Final phosphorus at x=0                 : {format_sci(result['ND'][0])} cm^-3")
        print(f"  Final boron at x=0                      : {format_sci(result['NA'][0])} cm^-3")
        print(f"  Surface polarity                        : {result['surface_polarity']}")

        print("\nIntegration depth used for dose / electrical model")
        if result["xj_cm"] is None:
            print(f"  No junction found; using wafer thickness: {WAFER_THICKNESS_UM:.4f} um")
        else:
            print(f"  Junction depth xj                       : {result['xj_cm'] * 1e4:.4f} um")
            print("  Using x = 0 to x = xj")

        print("\nIntegrated doses over the chosen depth")
        print(f"  Donor dose                              : {format_sci(result['donor_dose_cm2'])} cm^-2")
        print(f"  Acceptor dose                           : {format_sci(result['acceptor_dose_cm2'])} cm^-2")
        print(f"  Uniform background dose over same depth : {format_sci(result['background_uniform_dose_cm2'])} cm^-2")
        print(f"  Majority-carrier dose                   : {format_sci(result['carrier_dose'])} cm^-2")

        print("\nElectrical result")
        print(f"  Sheet conductance                       : {format_sci(result['Gsheet'])} S/sq")
        if SHOW_RS:
            rs_text = "None" if result["Rs"] is None else f"{result['Rs']:.4g} ohm/sq"
            print(f"  Expected Rs                             : {rs_text}")
        mu_text = "None" if result["mu_eff"] is None else f"{result['mu_eff']:.4g} cm^2/Vs"
        print(f"  Effective average mobility              : {mu_text}")
        print(f"  Mobility model                          : {MOBILITY_MODEL}")

    # ---------------- Plot ----------------
    fig, ax = plt.subplots(figsize=(11.5, 7.0), constrained_layout=True)

    for process_index, result in enumerate(results):
        process_name = result["name"]
        process_style = PROCESS_LINESTYLES[process_index % len(PROCESS_LINESTYLES)]
        history = result["history"]

        if SHOW_INTERMEDIATE_STEPS and len(history) > 2:
            n_mid = len(history) - 2
            for step_number, item in enumerate(history[1:-1], start=1):
                alpha = 0.08 + 0.22 * (step_number / max(n_mid, 1))
                P = ACTIVATION_PHOSPHORUS * item["phosphorus"]
                B = ACTIVATION_BORON * item["boron"]

                if np.max(P) > 0:
                    plot_profile(
                        ax, x_um, P, "_nolegend_", COLOR_PHOSPHORUS,
                        alpha=alpha, linestyle=process_style, linewidth=1.0
                    )
                if np.max(B) > 0:
                    plot_profile(
                        ax, x_um, B, "_nolegend_", COLOR_BORON,
                        alpha=alpha, linestyle=process_style, linewidth=1.0
                    )

        if np.max(result["ND"]) > 0:
            plot_profile(
                ax,
                x_um,
                result["ND"],
                f"{process_name} - phosphorus",
                COLOR_PHOSPHORUS,
                alpha=1.0,
                linestyle=process_style,
                linewidth=2.8,
            )

        if np.max(result["NA"]) > 0:
            plot_profile(
                ax,
                x_um,
                result["NA"],
                f"{process_name} - boron",
                COLOR_BORON,
                alpha=1.0,
                linestyle=process_style,
                linewidth=2.3,
            )

        if result["xj_cm"] is not None:
            ax.axvline(
                result["xj_cm"] * 1e4,
                color=COLOR_JUNCTION,
                linestyle=process_style,
                linewidth=1.5,
                alpha=0.75,
            )

    add_results_summary_box(ax, build_results_summary_lines(results))

    if SHOW_PROCESS_SUMMARY_BOX:
        process_summary_lines = build_process_summary_lines(
            PROCESSES, bg, BACKGROUND_CONCENTRATION_CM3
        )
        add_process_summary_box(ax, process_summary_lines)

    ax.set_title(PLOT_TITLE)
    ax.set_xlabel("Depth into Si (um)")
    ax.set_ylabel("Concentration (cm$^{-3}$)")
    ax.grid(True, which="both", alpha=0.3)
    apply_axis_limits(ax)
    ax.legend(fontsize=8, loc="upper left")
    plt.show()


if __name__ == "__main__":
    main()